"""Add time taken field to reports table

Revision ID: 428c5429419c
Revises: 84f17ee79218
Create Date: 2024-06-19 23:53:53.544436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428c5429419c'
down_revision: Union[str, None] = '84f17ee79218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_reports', sa.Column('time_taken', sa.Integer(), nullable=False), schema='results_analysis')
    op.alter_column('test_reports', 'date_time_of_answer',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='results_analysis')
    op.alter_column('test_reports', 'test_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='results_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_reports', 'test_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='results_analysis')
    op.alter_column('test_reports', 'date_time_of_answer',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='results_analysis')
    op.drop_column('test_reports', 'time_taken', schema='results_analysis')
    # ### end Alembic commands ###
