"""Initial database tables

Revision ID: cdf38d148e35
Revises: 
Create Date: 2024-05-24 09:41:58.219694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf38d148e35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychologists',
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cedula'),
    schema='patients'
    )
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('psychologist_cedula', sa.String(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('child_age', sa.Integer(), nullable=False),
    sa.Column('scholar_grade', sa.Integer(), nullable=False),
    sa.Column('child_sex', sa.String(length=1), nullable=False),
    sa.Column('date_time_of_answer', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id'),
    schema='results_analysis'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('psychologist_cedula', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='users_management'
    )
    op.create_index(op.f('ix_users_management_users_psychologist_cedula'), 'users', ['psychologist_cedula'], unique=True, schema='users_management')
    op.create_table('children',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('scholar_grade', sa.Integer(), nullable=False),
    sa.Column('psychologist_cedula', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_cedula'], ['patients.psychologists.cedula'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='patients'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('children', schema='patients')
    op.drop_index(op.f('ix_users_management_users_psychologist_cedula'), table_name='users', schema='users_management')
    op.drop_table('users', schema='users_management')
    op.drop_table('test_reports', schema='results_analysis')
    op.drop_table('test_sessions', schema='questionnaires')
    op.drop_table('psychologists', schema='patients')
    # ### end Alembic commands ###
